# Site settings
title: Lambda Draw Bot
description: > # this means to ignore newlines until "baseurl:"
  Lambda Pledge Class Build Project. We're building a robot that draws letters.
baseurl: "/Lambda-Draw-Bot" # the subpath of your site, e.g. /blog/
url: "http://jezhou.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
